-- api/sql/002_seed.sql
-- Seeds dining halls (Drexel) and an optional demo user

-- 1) Seed dining halls (edit names to match your UI list)
INSERT INTO dining_halls (school, name, location)
VALUES
  ('Drexel', 'Urban Eatery', 'Chestnut St'),
  ('Drexel', 'Hans Dining Hall', '33rd St'),
  ('Drexel', 'Northside Dining Hall', '34th St'),
  ('Drexel', 'Race Street Cafe', 'Race St'),
  ('Drexel', 'Creese Student Center', 'Market St')
ON CONFLICT (school, name) DO NOTHING;

-- 2) Optional: seed a demo user (password hash should be generated by backend in real usage)
-- You can skip this insert if you prefer only real signups.
-- This is a placeholder hash string; replace it only if you know what you're doing.
-- Recommended: do NOT rely on seeded users; use /auth/register instead.

-- INSERT INTO users (email, password_hash)
-- VALUES ('demo@ratemy.com', '$2b$10$REPLACE_WITH_REAL_BCRYPT_HASH')
-- ON CONFLICT (email) DO NOTHING;

-- 3) Optional: seed demo reviews
-- NOTE: Only works if you seeded a demo user above with a real hash.
-- Leaving this commented keeps your seed file safe.
--
-- INSERT INTO reviews (user_id, dining_hall_id, rating, comment)
-- SELECT u.id, d.id, 5, 'Great food and solid options.'
-- FROM users u, dining_halls d
-- WHERE u.email = 'demo@ratemy.com'
--   AND d.school = 'Drexel'
--   AND d.name = 'Urban Eatery'
-- ON CONFLICT (user_id, dining_hall_id) DO NOTHING;
